### ISSUE TITLE
Error when starting to mine: Gas required exceeds allowance.

### ISSUE THREAD

**Issue by sifotes** [PoWAdv/PoWAdv-miner#1]
Getting the following error when trying to mine. I have already tried using a gas price of 10, 15, and 20.
Already put 0.001 eth into the account.
```
 Error: Returned error: gas required exceeds allowance or always failing transaction    at Object.ErrorResponse (D:\snapshot\0xbitcoin-gpuminer\node_modules\web3-core-helpers\src\errors.js:0:0)    at D:\snapshot\0xbitcoin-gpuminer\node_modules\web3-core-requestmanager\src\index.js:0:0    at XMLHttpRequest.HttpProvider.send.request.onreadystatechange (D:\snapshot\0xbitcoin-gpuminer\node_modules\web3-providers-http\src\index.js:0:0)    at XMLHttpRequestEventTarget.dispatchEvent (D:\snapshot\0xbitcoin-gpuminer\node_modules\xhr2\lib\xhr2.js:64:18)    at XMLHttpRequest._setReadyState (D:\snapshot\0xbitcoin-gpuminer\node_modules\xhr2\lib\xhr2.js:354:12)    at XMLHttpRequest._onHttpResponseEnd (D:\snapshot\0xbitcoin-gpuminer\node_modules\xhr2\lib\xhr2.js:509:12)
at IncomingMessage.<anonymous> (D:\snapshot\0xbitcoin-gpuminer\node_modules\xhr2\lib\xhr2.js:469:24)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1056:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
```
Getting the same errors using the tokenminer.

**Comment by powether** [comment]
This can happen when you are using 0xBitcoin miner. They are using, estimated Gas limit for the mint function, 

`contractInstance.mint.estimateGas.....`

Instead this we are using constant Gas limit.

P.S: You can't start mining until the ETH reach 5349511th block.
